import { useQuery } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'
import { useAuthStore } from '@/stores/authStore'
import * as analyticsApi from '@/api/analytics'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { School, Users, TrendingUp, AlertCircle, Sparkles, MapPin } from 'lucide-react'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from 'recharts'

export default function DEODashboard() {
  const { t } = useTranslation()
  const user = useAuthStore((s) => s.user)
  // Hardcoded to 1 for demo purposes if district_id is not available
  const districtId = '1'

  const { data, isLoading, isError } = useQuery({
    queryKey: ['district-analytics', districtId],
    queryFn: () => analyticsApi.getDistrictAnalytics(districtId),
  })

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div className="flex flex-col gap-1">
        <h1 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-600 to-blue-600">
          District Overview, {user?.name}
        </h1>
        <p className="text-muted-foreground text-sm mt-1">
          High-level district insights and school performance aggregation
        </p>
      </div>

      {isError && (
        <Card className="border-destructive/50 bg-destructive/5">
          <CardContent className="flex items-center gap-3 p-6">
            <AlertCircle className="h-5 w-5 text-destructive" />
            <p className="text-sm text-destructive flex-1">{t('common.error')}</p>
          </CardContent>
        </Card>
      )}

      {/* AI Insights Section */}
      <Card className="border-none shadow-md bg-gradient-to-br from-indigo-500/10 to-purple-500/10 overflow-hidden relative">
        <div className="absolute top-0 right-0 p-6 opacity-20 pointer-events-none">
          <Sparkles className="h-24 w-24 text-primary" />
        </div>
        <CardHeader className="pb-2">
          <CardTitle className="text-lg flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-indigo-500" />
            AI District Insights
          </CardTitle>
          <CardDescription>Generated by Parakh AI</CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="space-y-2">
               <Skeleton className="h-4 w-full" />
               <Skeleton className="h-4 w-5/6" />
               <Skeleton className="h-4 w-4/6" />
            </div>
          ) : data?.insights ? (
            <div className="space-y-4">
               <div>
                  <p className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-2">Strengths</p>
                  <ul className="space-y-1">
                     {data.insights.strengths?.map((s: string, i: number) => (
                        <li key={i} className="text-sm flex gap-2 items-start">
                           <span className="text-green-500 mt-0.5">•</span> <span>{s}</span>
                        </li>
                     ))}
                  </ul>
               </div>
               <div>
                  <p className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-2">Areas for Improvement</p>
                  <ul className="space-y-1">
                     {data.insights.weaknesses?.map((w: string, i: number) => (
                        <li key={i} className="text-sm flex gap-2 items-start">
                           <span className="text-amber-500 mt-0.5">•</span> <span>{w}</span>
                        </li>
                     ))}
                  </ul>
               </div>
               <div>
                  <p className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-2">Policy Recommendations</p>
                  <p className="text-sm text-foreground bg-background/50 p-3 rounded-lg border border-primary/20">
                     {data.insights.recommendations?.[0] || 'Provide targeted training for underperforming schools.'}
                  </p>
               </div>
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">No AI insights generated yet.</p>
          )}
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card className="shadow-sm">
          <CardContent className="p-6 flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Total Schools</p>
              <p className="text-3xl font-bold mt-1 text-foreground">
                {isLoading ? <Skeleton className="h-8 w-16" /> : data?.summary?.total_schools || 0}
              </p>
            </div>
            <div className="p-3 bg-blue-500/10 rounded-xl text-blue-500"><School className="h-6 w-6" /></div>
          </CardContent>
        </Card>
        <Card className="shadow-sm">
          <CardContent className="p-6 flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Total Students</p>
              <p className="text-3xl font-bold mt-1 text-foreground">
                {isLoading ? <Skeleton className="h-8 w-16" /> : data?.summary?.total_students || 0}
              </p>
            </div>
            <div className="p-3 bg-cyan-500/10 rounded-xl text-cyan-500"><Users className="h-6 w-6" /></div>
          </CardContent>
        </Card>
        <Card className="shadow-sm">
          <CardContent className="p-6 flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">District Average</p>
              <p className="text-3xl font-bold mt-1 text-emerald-500">
                {isLoading ? <Skeleton className="h-8 w-16" /> : `${data?.summary?.average_score?.toFixed(1) || 0}%`}
              </p>
            </div>
            <div className="p-3 bg-emerald-500/10 rounded-xl text-emerald-500"><TrendingUp className="h-6 w-6" /></div>
          </CardContent>
        </Card>
      </div>

      <Card className="shadow-sm">
         <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
               <MapPin className="h-5 w-5" />
               School Performance Comparison
            </CardTitle>
         </CardHeader>
         <CardContent>
            {isLoading ? (
               <Skeleton className="h-[300px] w-full" />
            ) : data?.schools && data.schools.length > 0 ? (
               <div className="h-[300px] w-full">
                  <ResponsiveContainer width="100%" height="100%">
                     <BarChart data={data.schools} margin={{ top: 10, right: 10, left: -20, bottom: 20 }}>
                        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="hsl(var(--muted))" />
                        <XAxis 
                           dataKey="name" 
                           axisLine={false} 
                           tickLine={false} 
                           tick={{fill: 'hsl(var(--muted-foreground))', fontSize: 12}}
                           angle={-45}
                           textAnchor="end"
                           height={60}
                        />
                        <YAxis 
                           axisLine={false} 
                           tickLine={false} 
                           tick={{fill: 'hsl(var(--muted-foreground))', fontSize: 12}}
                           domain={[0, 100]}
                        />
                        <Tooltip 
                           contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                           cursor={{fill: 'hsl(var(--muted)/0.5)'}}
                        />
                        <Bar dataKey="average_score" radius={[4, 4, 0, 0]} barSize={40}>
                           {data.schools.map((entry: any, index: number) => (
                              <Cell key={`cell-${index}`} fill={`hsl(var(--primary) / ${0.5 + (entry.average_score / 200)})`} />
                           ))}
                        </Bar>
                     </BarChart>
                  </ResponsiveContainer>
               </div>
            ) : (
               <p className="text-center text-muted-foreground py-10">No school data available for this district.</p>
            )}
         </CardContent>
      </Card>
    </div>
  )
}
