import { useQuery } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'
import { useAuthStore } from '@/stores/authStore'
import * as analyticsApi from '@/api/analytics'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { Users, BookOpen, GraduationCap, AlertCircle, Sparkles, TrendingUp } from 'lucide-react'
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts'

export default function PrincipalDashboard() {
  const { t } = useTranslation()
  const user = useAuthStore((s) => s.user)
  const schoolId = user?.school_id ? String(user.school_id) : '1' // Fallback to 1 for testing

  const { data, isLoading, isError } = useQuery({
    queryKey: ['school-analytics', schoolId],
    queryFn: () => analyticsApi.getSchoolAnalytics(schoolId),
    enabled: !!schoolId,
  })

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div className="flex flex-col gap-1">
        <h1 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-emerald-600 to-teal-500">
          Principal Dashboard, {user?.name}
        </h1>
        <p className="text-muted-foreground text-sm mt-1">
          School-wide learning trends and AI-driven performance insights
        </p>
      </div>

      {isError && (
        <Card className="border-destructive/50 bg-destructive/5">
          <CardContent className="flex items-center gap-3 p-6">
            <AlertCircle className="h-5 w-5 text-destructive" />
            <p className="text-sm text-destructive flex-1">{t('common.error')}</p>
          </CardContent>
        </Card>
      )}

      {/* AI Insights Section */}
      <Card className="border-none shadow-md bg-gradient-to-br from-emerald-500/10 to-teal-500/10 overflow-hidden relative">
        <div className="absolute top-0 right-0 p-6 opacity-20 pointer-events-none">
          <Sparkles className="h-24 w-24 text-emerald-500" />
        </div>
        <CardHeader className="pb-2">
          <CardTitle className="text-lg flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-emerald-500" />
            AI School Insights
          </CardTitle>
          <CardDescription>Generated by Parakh AI</CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="space-y-2">
               <Skeleton className="h-4 w-full" />
               <Skeleton className="h-4 w-5/6" />
               <Skeleton className="h-4 w-4/6" />
            </div>
          ) : data?.insights ? (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
               <div>
                  <p className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-2">Strengths</p>
                  <ul className="space-y-1">
                     {data.insights.strengths?.map((s: string, i: number) => (
                        <li key={i} className="text-sm flex gap-2 items-start">
                           <span className="text-emerald-500 mt-0.5">•</span> <span>{s}</span>
                        </li>
                     ))}
                  </ul>
               </div>
               <div>
                  <p className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-2">Areas for Improvement</p>
                  <ul className="space-y-1">
                     {data.insights.weaknesses?.map((w: string, i: number) => (
                        <li key={i} className="text-sm flex gap-2 items-start">
                           <span className="text-rose-500 mt-0.5">•</span> <span>{w}</span>
                        </li>
                     ))}
                  </ul>
               </div>
               <div className="md:col-span-2">
                  <p className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-2">Recommended Actions</p>
                  <p className="text-sm text-foreground bg-background/50 p-3 rounded-lg border border-emerald-500/20">
                     {data.insights.recommendations?.[0] || 'Focus on foundational concepts in math and science.'}
                  </p>
               </div>
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">No AI insights generated yet.</p>
          )}
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <Card className="shadow-sm">
          <CardContent className="p-6 flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Total Classes</p>
              <p className="text-3xl font-bold mt-1 text-foreground">
                {isLoading ? <Skeleton className="h-8 w-16" /> : data?.summary?.total_classes || 0}
              </p>
            </div>
            <div className="p-3 bg-blue-500/10 rounded-xl text-blue-500"><BookOpen className="h-6 w-6" /></div>
          </CardContent>
        </Card>
        <Card className="shadow-sm">
          <CardContent className="p-6 flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Total Students</p>
              <p className="text-3xl font-bold mt-1 text-foreground">
                {isLoading ? <Skeleton className="h-8 w-16" /> : data?.summary?.total_students || 0}
              </p>
            </div>
            <div className="p-3 bg-cyan-500/10 rounded-xl text-cyan-500"><Users className="h-6 w-6" /></div>
          </CardContent>
        </Card>
        <Card className="shadow-sm">
          <CardContent className="p-6 flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Assessments</p>
              <p className="text-3xl font-bold mt-1 text-foreground">
                {isLoading ? <Skeleton className="h-8 w-16" /> : data?.summary?.total_assessments || 0}
              </p>
            </div>
            <div className="p-3 bg-purple-500/10 rounded-xl text-purple-500"><GraduationCap className="h-6 w-6" /></div>
          </CardContent>
        </Card>
        <Card className="shadow-sm">
          <CardContent className="p-6 flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">School Average</p>
              <p className="text-3xl font-bold mt-1 text-emerald-500">
                {isLoading ? <Skeleton className="h-8 w-16" /> : `${data?.summary?.average_score?.toFixed(1) || 0}%`}
              </p>
            </div>
            <div className="p-3 bg-emerald-500/10 rounded-xl text-emerald-500"><TrendingUp className="h-6 w-6" /></div>
          </CardContent>
        </Card>
      </div>

      <Card className="shadow-sm">
         <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
               <TrendingUp className="h-5 w-5" />
               Class Performance Comparison
            </CardTitle>
            <CardDescription>Average scores across different classes</CardDescription>
         </CardHeader>
         <CardContent>
            {isLoading ? (
               <Skeleton className="h-[300px] w-full" />
            ) : data?.classes && data.classes.length > 0 ? (
               <div className="h-[300px] w-full">
                  <ResponsiveContainer width="100%" height="100%">
                     <LineChart data={data.classes} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="hsl(var(--muted))" />
                        <XAxis 
                           dataKey="name" 
                           axisLine={false} 
                           tickLine={false} 
                           tick={{fill: 'hsl(var(--muted-foreground))', fontSize: 12}}
                           dy={10}
                        />
                        <YAxis 
                           axisLine={false} 
                           tickLine={false} 
                           tick={{fill: 'hsl(var(--muted-foreground))', fontSize: 12}}
                           domain={[0, 100]}
                        />
                        <Tooltip 
                           contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                        />
                        <Line 
                           type="monotone" 
                           dataKey="average_score" 
                           stroke="hsl(var(--emerald-500))" 
                           strokeWidth={3}
                           dot={{ r: 4, fill: 'hsl(var(--background))', strokeWidth: 2 }}
                           activeDot={{ r: 6 }}
                        />
                     </LineChart>
                  </ResponsiveContainer>
               </div>
            ) : (
               <p className="text-center text-muted-foreground py-10">No class data available for this school.</p>
            )}
         </CardContent>
      </Card>
    </div>
  )
}
